package com.rinehartlabs;
unit BasicRuleUnit;

import com.rinehartlabs.dto.Stat;

rule "add stat"
when
    $point: /statPoints
    accumulate( /modifiers[ type == $point.type, $value : value ];
        $modifiers : sum( $value ) )
then
    System.out.printf("add stat with modifier: %s, %s%n", $point, $modifiers);
    stats.addLogical(new Stat($point.type(), $point.value() + $modifiers));
end

rule "display stat"
when
    $stat: /stats
then
    System.out.printf("display stat: %s%n", $stat);
end

query FindStats
    $stat: /stats
end